name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  http:
  flutter_dotenv:
  flutter_markdown:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  shared_preferences: 

flutter:
  uses-material-design: true
  assets:
    - .env
